[package]
name = "client"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]

[dependencies]
tokio = { version = "1.17.0", features = ["sync"] }
blake2 = "0.9"
tracing = "0.1.31"
tokio-util = { version = "0.7.0", features = ["codec"] }
serde = { version = "1.0.136", features = ["derive"] }
futures = "0.3.21"
rocksdb = { version = "0.18.0", features = ["snappy", "lz4", "zstd", "zlib"], default-features = false }
bytes = "1.1.0"
bincode = "1.3.3"
thiserror = "1.0.30"
async-trait = "0.1.53"

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "808de09203d147b43d59114b8afd9e51cbcf5778"}

worker = { path = "../worker" }
crypto = { path = "../crypto" }
config = { path = "../config" }
primary = { path = "../primary" }
consensus = { path = "../consensus" }

[dev-dependencies]
rand = "0.7.3"
temp_testdir = "0.2"