[workspace]
members = ["config", "consensus", "crypto", "dag", "examples", "executor", "network", "node", "primary", "test_utils", "types", "worker", "workspace-hack"]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true
