[workspace]
members = ["dag", "primary", "node", "crypto", "worker", "consensus", "network", "config", "executor"]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true