[workspace]
members = ["config", "consensus", "crypto", "dag", "executor", "network", "node", "primary", "test_utils", "types", "worker"]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true
