# cyclomatic complexity is not always useful
cognitive-complexity-threshold = 100
# types are used for safety encoding
type-complexity-threshold = 10000
# big constructors
too-many-arguments-threshold =  15
disallowed-methods = [
    # unbounded channels are for expert use only
    { path = "tokio::sync::mpsc::unbounded", reason = "use a bounded channel instead" },
    { path = "futures::channel::mpsc::unbounded", reason = "use a bounded channel instead" },
    { path = "futures_channel::mpsc::unbounded", reason = "use a bounded channel instead" },
]
