var sourcesIndex = {};
sourcesIndex["config"] = {"name":"","files":["duration_format.rs","lib.rs","utils.rs"]};
sourcesIndex["consensus"] = {"name":"","files":["bullshark.rs","consensus.rs","dag.rs","lib.rs","metrics.rs","subscriber.rs","tusk.rs","utils.rs"]};
sourcesIndex["crypto"] = {"name":"","files":["bls12381.rs","ed25519.rs","hkdf.rs","lib.rs","pubkey_bytes.rs","secp256k1.rs","serde_helpers.rs","traits.rs"]};
sourcesIndex["dag"] = {"name":"","files":["bft.rs","lib.rs","node_dag.rs"]};
sourcesIndex["demo_client"] = {"name":"","files":["demo_client.rs"]};
sourcesIndex["executor"] = {"name":"","files":["batch_loader.rs","core.rs","errors.rs","lib.rs","state.rs","subscriber.rs"]};
sourcesIndex["network"] = {"name":"","files":["bounded_executor.rs","lib.rs","primary.rs","retry.rs","worker.rs"]};
sourcesIndex["node"] = {"name":"","files":["execution_state.rs","lib.rs","metrics.rs","restarter.rs"]};
sourcesIndex["primary"] = {"name":"","dirs":[{"name":"block_synchronizer","files":["handler.rs","mock.rs","mod.rs","peers.rs","responses.rs"]},{"name":"grpc_server","files":["configuration.rs","metrics.rs","mod.rs","proposer.rs","validator.rs"]}],"files":["aggregators.rs","block_remover.rs","block_waiter.rs","certificate_waiter.rs","core.rs","header_waiter.rs","helper.rs","lib.rs","metrics.rs","payload_receiver.rs","primary.rs","proposer.rs","state_handler.rs","synchronizer.rs","utils.rs"]};
sourcesIndex["test_utils"] = {"name":"","files":["cluster.rs","lib.rs"]};
sourcesIndex["types"] = {"name":"","dirs":[{"name":"generated","files":["narwhal.rs"]}],"files":["consensus.rs","error.rs","lib.rs","primary.rs","proto.rs","worker.rs"]};
sourcesIndex["worker"] = {"name":"","files":["batch_maker.rs","helper.rs","lib.rs","metrics.rs","primary_connector.rs","processor.rs","quorum_waiter.rs","synchronizer.rs","worker.rs"]};
sourcesIndex["workspace_hack"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
