[package]
name = "types"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.2.1"
derive_builder = "0.11.2"
ed25519-dalek = "1.0.1"
futures = "0.3.21"
prometheus = "0.13.1"
proptest = "1.0.0"
proptest-derive = "0.3.0"
prost = "0.10.4"
rand = "0.8.5"
serde = { version = "1.0.142", features = ["derive"] }
signature = "1.5.0"
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "d965a5a795dcdb4d1c7964acf556bc249fdc58aa" }
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tonic = { version = "0.7.2", features = ["tls"] }
indexmap = { version = "1.9.1", features = ["serde"] }

config = { path = "../config" }
crypto = { path = "../crypto" }
dag = { path = "../dag" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }



[dev-dependencies]
hex = "0.4.3"
serde_test = "1.0.142"
criterion = "0.3.6"

[build-dependencies]
rustversion = "1.0.9"
prost-build = "0.10.4"
tonic-build = { version = "0.7.2", features = [ "prost", "transport" ] }

[features]
default = []
test = []

[[bench]]
name = "batch_digest"
harness = false
