[package]
name = "types"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.1.0"
derive_builder = "0.11.2"
ed25519-dalek = "1.0.1"
rand = "0.7.3"
serde = { version = "1.0.136", features = ["derive"] }
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "808de09203d147b43d59114b8afd9e51cbcf5778" }
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["sync", "rt", "macros"] }

config = { path = "../config" }
crypto = { path = "../crypto" }

