[package]
name = "dag"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
crypto  = { path = "../crypto" }
dashmap = "5.3.4"
either = "1.7.0"
itertools = "0.10.3"
serde = "1.0.139"
thiserror = "1.0.31"
arc-swap = "1.5.0"
once_cell = "1.13.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
hex = "0.4.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"
rayon = "1.5.3"
