[package]
name = "dag"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
crypto  = { path = "../crypto" }
dashmap = "5.2.0"
either = "1.6.1"
itertools = "0.10.3"
rayon = "1.5.2"
serde = "1.0.136"
serde_with = "1.12.1"
thiserror = "1.0.30"
arc-swap = "1.5.0"
once_cell = "1.10.0"

[dev-dependencies]
hex = "0.4.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"
rayon = "1.5.2"
