[package]
name = "dag"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
arc-swap = "1.5.1"
fastcrypto = "0.1.2"
dashmap = "5.4.0"
either = "1.8.0"
itertools = "0.10.4"
once_cell = "1.14.0"
rayon = "1.5.3"
serde = "1.0.144"
thiserror = "1.0.34"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
hex = "0.4.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"
rayon = "1.5.3"
