[package]
name = "network"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.57"
backoff = { version = "0.4.0", features = ["tokio"] }
bytes = "1.2.1"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "c022a2ae23ca7cc2778293fd3b1db42e8cd02d3b" }
futures = "0.3.24"
multiaddr = "0.14.0"
prometheus = "0.13.1"
rand = { version = "0.8.5", features = ["small_rng"] }
thiserror = "1.0.34"
tokio = { version = "1.20.1", features = ["rt", "net", "sync", "macros", "time"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tonic = { version = "0.7.2", features = ["tls"] }
tracing = "0.1.36"
types = { path = "../types" }
crypto = { path = "../crypto" }

serde = "1.0.144"
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "44ef8a4dfd773038ff331c3034239a6a121b3242" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
eyre = "0.6.8"

anemo = { git = "https://github.com/mystenlabs/anemo.git", rev = "6278d0fa78147a49ff2cb9dd2e45e763886be0a0" }
anyhow = "1.0.64"

[dev-dependencies]
bincode = "1.3.3"
test_utils = { path = "../test_utils" }
