[package]
name = "network"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.52"
bytes = "1.1.0"
futures = "0.3.21"
rand = { version = "0.7.3", features = ["small_rng"] }
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["rt", "net", "sync", "macros", "time"] }
tokio-util = { version = "0.7.0", features = ["codec"] }
tracing = { version = "0.1.31", features = ["log"] }

[dev-dependencies]
bincode = "1.3.3"
