[package]
name = "config"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
match_opt = "0.1.2"
multiaddr = "0.14.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_with = "2.0.1"
serde_json = "1.0.85"
thiserror = "1.0.34"
tracing = "0.1.36"
arc-swap = { version = "1.5.1", features = ["serde"] }

fastcrypto = "0.1.2"
crypto = { path = "../crypto" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
rand = "0.8.5"

[dev-dependencies]
insta = { version = "1.19.1", features = ["json"] }
rand = "0.8.5"
tempfile = "3.3.0"
tracing-test = "0.2.3"

test_utils = { path = "../test_utils" }
