[package]
name = "config"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Alberto Sonnino <asonnino@fb.com>"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.24"
serde_json = "1.0.64"
tracing = { version = "0.1", features = ["log"] }

crypto = { path = "../crypto" }
