[package]
name = "config"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"
tracing = "0.1.35"
multiaddr = "0.14.0"

crypto = { path = "../crypto" }
arc-swap = { version = "1.5.0", features = ["serde"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
insta = "1.16.0"
rand = "0.7.3"
tempfile = "3.3.0"
tracing-test = "0.2.3"

test_utils = { path = "../test_utils"}
