[package]
name = "config"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"


[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
serde_json = "1.0.79"
tracing = { version = "0.1.31", features = ["log"] }

crypto = { path = "../crypto" }

