[package]
name = "demo"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[[bin]]
name = "demo_client"
path = "src/demo_client.rs"

[dependencies]
clap = "2.34"
tonic = "0.7.2"
prost = "0.10.4"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
base64 = "0.13.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[build-dependencies]
tonic-build = "0.7.2"

[features]
benchmark = []
