[package]
name = "primary"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.56"
base64 = "0.13.0"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.2.0"
config = { path = "../config" }
derive_builder = "0.11.2"
ed25519-dalek = "1.0.1"
futures = "0.3.21"
itertools = "0.10.3"
multiaddr = "0.14.0"
prost = "0.10.4"
rand = { version = "0.7.3", features = ["small_rng"] }
serde = { version = "1.0.139", features = ["derive"] }
thiserror = "1.0.31"
tokio = { version = "1.20.1", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tonic = "0.7.2"
tower = "0.4.13"
tracing = "0.1.35"
dhat = { version = "0.3", optional = true }

consensus = { path = "../consensus" }
crypto = { path = "../crypto" }
network = { path = "../network" }
types = { path = "../types" }

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "123c9e40b529315e1c1d91a54fb717111c3e349c" }
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "123c9e40b529315e1c1d91a54fb717111c3e349c" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
prometheus = "0.13.1"
once_cell = "1.13.0"
dashmap = "5.3.4"

[dev-dependencies]
arc-swap = { version = "1.5.0", features = ["serde"] }
itertools = "0.10.3"
mockall = "0.11.2"
node = { path = "../node" }
tempfile = "3.3.0"
test_utils = { path = "../test_utils" }
tracing-test = "0.2.3"
worker = { path = "../worker" }
async-trait = "0.1.56"
executor = { path = "../executor" }
thiserror = "1.0.31"
tracing = "0.1.35"
telemetry-subscribers = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "123c9e40b529315e1c1d91a54fb717111c3e349c" }

[features]
benchmark = []
dhat-heap = ["dhat"]    # if you are doing heap profiling
