[package]
name = "primary"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.57"
base64 = "0.13.0"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.2.1"
config = { path = "../config" }
dashmap = "5.4.0"
derive_builder = "0.11.2"
dhat = { version = "0.3.0", optional = true }
futures = "0.3.24"
itertools = "0.10.3"
multiaddr = "0.14.0"
once_cell = "1.13.1"
prometheus = "0.13.1"
prost = "0.10.4"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.33"
tokio = { version = "1.20.1", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tonic = "0.7.2"
tower = "0.4.13"
tracing = "0.1.36"
tap = "1.0.1"

consensus = { path = "../consensus" }
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "c022a2ae23ca7cc2778293fd3b1db42e8cd02d3b" }
crypto = { path = "../crypto" }
network = { path = "../network" }
types = { path = "../types" }
storage = { path = "../storage" }
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "696fa25982acdc87ab64ec6a33cb111edc63a331" }

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "696fa25982acdc87ab64ec6a33cb111edc63a331" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
async-trait = "0.1.57"
executor = { path = "../executor" }
indexmap = { version = "1.9.1", features = ["serde"] }
itertools = "0.10.3"
mockall = "0.11.2"
node = { path = "../node" }
telemetry-subscribers = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "696fa25982acdc87ab64ec6a33cb111edc63a331" }
tempfile = "3.3.0"
test_utils = { path = "../test_utils" }
thiserror = "1.0.33"
tracing = "0.1.36"
tracing-test = "0.2.3"
worker = { path = "../worker" }
storage = { path = "../storage" }

[features]
benchmark = []
dhat-heap = ["dhat"]    # if you are doing heap profiling
