[package]
name = "primary"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.56"
base64 = "0.13.0"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.1.0"
config = { path = "../config" }
derive_builder = "0.11.2"
ed25519-dalek = "1.0.1"
futures = "0.3.21"
itertools = "0.10.3"
multiaddr = "0.14.0"
prost = "0.10.4"
rand = { version = "0.7.3", features = ["small_rng"] }
serde = { version = "1.0.138", features = ["derive"] }
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tonic = "0.7.2"
tower = "0.4.12"
tracing = "0.1.34"

consensus = { path = "../consensus" }
crypto = { path = "../crypto" }
network = { path = "../network" }
types = { path = "../types" }

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "16f00004fc7673f84b40615be19f907a0b3e1d5b" }
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "16f00004fc7673f84b40615be19f907a0b3e1d5b" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
prometheus = "0.13.1"
once_cell = "1.12.1"

[dev-dependencies]
arc-swap = { version = "1.5.0", features = ["serde"] }
itertools = "0.10.3"
mockall = "0.11.1"
node = { path = "../node" }
tempfile = "3.3.0"
test_utils = { path = "../test_utils" }
tracing-test = "0.2.2"
worker = { path = "../worker" }

[features]
benchmark = []
