[package]
name = "primary"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.53"
base64 = "0.13.0"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.1.0"
config = { path = "../config" }
derive_builder = "0.11.2"
ed25519-dalek = "1.0.1"
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "808de09203d147b43d59114b8afd9e51cbcf5778" }
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.1", features = ["codec"] }
tracing = { version = "0.1.34", features = ["log"] }
rand = { version = "0.8.5", features = ["small_rng"] }

crypto = { path = "../crypto" }
network = { path = "../network" }
types = { path = "../types" }

[dev-dependencies]
tempfile = "3.3.0"
types = { path = "../types", features = ["test"] }

[features]
benchmark = []
