[package]
name = "primary"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Libra <oncall+libra@xmail.facebook.com>"]
publish = false
edition = "2018"

[dependencies]
futures = "0.3.19"
serde = { version = "1.0.132", features = ["derive"] }
tokio = { version = "1.15.0", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.6.9", features = ["codec"] }
ed25519-dalek = "1.0.1"
thiserror = "1.0.30"
bincode = "1.3.3"
bytes = "1.1.0"
async-recursion = "0.3.2"
async-trait = "0.1.52"
tracing = { version = "0.1.29", features = ["log"] }

crypto = { path = "../crypto" }
store = { path = "../store" }
config = { path = "../config" }
network = { path = "../network" }

[dev-dependencies]
rand = "0.7.3"
tempfile = "3.2.0"

[features]
benchmark = []
