[package]
name = "node"
version = "0.1.0"
license = "Apache-2.0"
authors = ["George Danezis <gdanezis@fb.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
tokio-util = { version = "0.6.9", features = ["codec"] }
clap = "2.34.0"
bytes = "1.1.0"
bincode = "1.3.3"
anyhow = "1.0.52"
rand = "0.7.3"
futures = "0.3.19"
tracing = { version = "0.1.29", features = ["log"] }
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.4", features = ["time", "env-filter"] }

config = { path = "../config" }
store = { path = "../store" }
crypto = { path = "../crypto" }
primary = { path = "../primary" }
worker = { path = "../worker" }
consensus = { path = "../consensus" }
cfg-if = "1.0.0"

[features]
benchmark = ["worker/benchmark", "primary/benchmark", "consensus/benchmark"]

[[bin]]         
name = "benchmark_client"   
path = "src/benchmark_client.rs" 
required-features = ["benchmark"] 
