[package]
name = "narwhal-node"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
async-trait = "0.1.57"
bincode = "1.3.3"
bytes = "1.2.1"
cfg-if = "1.0.0"
clap = "2.34"
dhat = { version = "0.3.1", optional = true }
futures = "0.3.24"
multiaddr = "0.14.0"
mysten-network = "0.1.0"
rand = "0.8.5"
store = { version = "0.1.0", package = "typed-store"}
telemetry-subscribers = "0.1.0"
thiserror = "1.0.35"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.10"
tokio-util = { version = "0.7.4", features = ["codec"] }
tracing = "0.1.36"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.15", features = ["time", "env-filter"] }
url = "2.3.1"
axum = "0.5.16"
itertools = "0.10.4"

config = { path = "../config", package = "narwhal-config" }
consensus = { path = "../consensus", package = "narwhal-consensus" }
fastcrypto = "0.1.2"
crypto = { path = "../crypto", package = "narwhal-crypto" }
executor = { path = "../executor", package = "narwhal-executor" }
network = { path = "../network", package = "narwhal-network" }
primary = { path = "../primary", package = "narwhal-primary" }
prometheus = "0.13.2"
storage = { path = "../storage", package = "narwhal-storage" }
types = { path = "../types", package = "narwhal-types" }
worker = { path = "../worker", package = "narwhal-worker" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
eyre = "0.6.8"

anemo = { git = "https://github.com/mystenlabs/anemo.git", rev = "b145cbcf4a1917197e2b9ee6a1523afdb623dbf2" }

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "1.3.0"
serde-reflection = "0.3.6"
serde_yaml = "0.8.26"
structopt = "0.3.26"
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }

[features]
benchmark = ["worker/benchmark", "primary/benchmark", "consensus/benchmark"]
dhat-heap = ["dhat"]    # if you are doing heap profiling
trace_transaction = ["worker/trace_transaction"]

[[bin]]
name = "node"
path = "src/main.rs"

[[bin]]
name = "benchmark_client"
path = "src/benchmark_client.rs"
required-features = ["benchmark"]

[[example]]
name = "generate-format"
path = "src/generate_format.rs"
test = false
