[package]
name = "node"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
async-trait = "0.1.57"
bincode = "1.3.3"
bytes = "1.2.1"
cfg-if = "1.0.0"
clap = "2.34"
dhat = { version = "0.3.0", optional = true }
futures = "0.3.24"
multiaddr = "0.14.0"
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "d96230a9272c322a7eefac49708aadfff1eed77e" }
rand = "0.8.5"
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "d96230a9272c322a7eefac49708aadfff1eed77e" }
telemetry-subscribers = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "d96230a9272c322a7eefac49708aadfff1eed77e" }
thiserror = "1.0.34"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.9"
tokio-util = { version = "0.7.3", features = ["codec"] }
tracing = "0.1.36"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.15", features = ["time", "env-filter"] }
url = "2.2.2"
axum = "0.5.15"
itertools = "0.10.3"

config = { path = "../config" }
consensus = { path = "../consensus" }
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "c022a2ae23ca7cc2778293fd3b1db42e8cd02d3b" }
crypto = { path = "../crypto" }
executor = { path = "../executor" }
network = { path = "../network" }
primary = { path = "../primary" }
prometheus = "0.13.1"
storage = { path = "../storage" }
types = { path = "../types" }
worker = { path = "../worker" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
eyre = "0.6.8"

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "1.3.0"
serde-reflection = "0.3.6"
serde_yaml = "0.8.26"
structopt = "0.3.26"
test_utils = { path = "../test_utils" }

[features]
benchmark = ["worker/benchmark", "primary/benchmark", "consensus/benchmark"]
dhat-heap = ["dhat"]    # if you are doing heap profiling

[[bin]]
name = "benchmark_client"
path = "src/benchmark_client.rs"
required-features = ["benchmark"]

[[example]]
name = "generate-format"
path = "src/generate_format.rs"
test = false
