[package]
name = "node"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
async-trait = "0.1.57"
bincode = "1.3.3"
bytes = "1.2.1"
cfg-if = "1.0.0"
clap = "2.34"
dhat = { version = "0.3.0", optional = true }
futures = "0.3.24"
multiaddr = "0.14.0"
mysten-network = "0.1.0"
rand = "0.8.5"
store = { version = "0.1.0", package = "typed-store"}
telemetry-subscribers = "0.1.0"
thiserror = "1.0.34"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.9"
tokio-util = { version = "0.7.4", features = ["codec"] }
tracing = "0.1.36"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.15", features = ["time", "env-filter"] }
url = "2.3.1"
axum = "0.5.16"
itertools = "0.10.4"

config = { path = "../config" }
consensus = { path = "../consensus" }
fastcrypto = "0.1.2"
crypto = { path = "../crypto" }
executor = { path = "../executor" }
network = { path = "../network" }
primary = { path = "../primary" }
prometheus = "0.13.2"
storage = { path = "../storage" }
types = { path = "../types" }
worker = { path = "../worker" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
eyre = "0.6.8"

anemo = { git = "https://github.com/mystenlabs/anemo.git", rev = "6278d0fa78147a49ff2cb9dd2e45e763886be0a0" }

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "1.3.0"
serde-reflection = "0.3.6"
serde_yaml = "0.8.26"
structopt = "0.3.26"
test_utils = { path = "../test_utils" }

[features]
benchmark = ["worker/benchmark", "primary/benchmark", "consensus/benchmark"]
dhat-heap = ["dhat"]    # if you are doing heap profiling

[[bin]]
name = "benchmark_client"
path = "src/benchmark_client.rs"
required-features = ["benchmark"]

[[example]]
name = "generate-format"
path = "src/generate_format.rs"
test = false
