[package]
name = "node"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bincode = "1.3.3"
bytes = "1.1.0"
cfg-if = "1.0.0"
clap = "2.34"
futures = "0.3.21"
rand = "0.7.3"
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "7c247967e5a5abd59ecaa75bc62b05bcdf4503fe" }
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.7.1", features = ["codec"] }
tracing = { version = "0.1.34", features = ["log"] }
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.11", features = ["time", "env-filter"] }
url = "2.2.2"

config = { path = "../config" }
consensus = { path = "../consensus" }
crypto = { path = "../crypto" }
executor = { path = "../executor" }
primary = { path = "../primary" }
types = { path = "../types" }
worker = { path = "../worker" }

[dev-dependencies]
ed25519-dalek = "1.0.1"
hex = "0.4.3"
pretty_assertions = "1.2.1"
serde-reflection = "0.3.5"
serde_yaml = "0.8.23"
structopt = "0.3.26"

[features]
benchmark = ["worker/benchmark", "primary/benchmark", "consensus/benchmark"]

[[bin]]         
name = "benchmark_client"   
path = "src/benchmark_client.rs" 
required-features = ["benchmark"] 

[[example]]
name = "generate-format"
path = "src/generate_format.rs"
test = false
