[package]
name = "node"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.58"
arc-swap = { version = "1.5.0", features = ["serde"] }
async-trait = "0.1.56"
bincode = "1.3.3"
bytes = "1.2.0"
cfg-if = "1.0.0"
clap = "2.34"
futures = "0.3.21"
rand = "0.7.3"
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "123c9e40b529315e1c1d91a54fb717111c3e349c" }
thiserror = "1.0.31"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.9"
tokio-util = { version = "0.7.3", features = ["codec"] }
tracing = "0.1.35"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.15", features = ["time", "env-filter"] }
telemetry-subscribers = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "123c9e40b529315e1c1d91a54fb717111c3e349c" }
url = "2.2.2"
dhat = { version = "0.3", optional = true }

config = { path = "../config" }
consensus = { path = "../consensus" }
crypto = { path = "../crypto" }
executor = { path = "../executor" }
primary = { path = "../primary" }
types = { path = "../types" }
worker = { path = "../worker" }
network = { path = "../network" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
axum = "0.5.14"
prometheus = "0.13.1"

[dev-dependencies]
ed25519-dalek = "1.0.1"
hex = "0.4.3"
pretty_assertions = "1.2.1"
serde-reflection = "0.3.6"
serde_yaml = "0.8.26"
structopt = "0.3.26"
test_utils = { path = "../test_utils" }
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "c6dc7a23a40b3517f138d122a76d3bc15f844f67" }

[features]
benchmark = ["worker/benchmark", "primary/benchmark", "consensus/benchmark"]
dhat-heap = ["dhat"]    # if you are doing heap profiling

[[bin]]         
name = "benchmark_client"   
path = "src/benchmark_client.rs" 
required-features = ["benchmark"] 

[[example]]
name = "generate-format"
path = "src/generate_format.rs"
test = false
