[package]
name = "executor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]

[dependencies]
async-trait = "0.1.57"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.2.1"
config = { path = "../config" }
consensus = { path = "../consensus" }
crypto = { path = "../crypto" }
futures = "0.3.21"
multiaddr = "0.14.0"
primary = { path = "../primary" }
serde = { version = "1.0.143", features = ["derive"] }
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["sync"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tonic = "0.7.2"
tracing = "0.1.36"
prometheus = "0.13.1"
backoff = { version = "0.4.0", features = ["tokio"] }

types = { path = "../types" }
worker = { path = "../worker" }
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "8d090689be14078f2ca41c356e7bbc0af21f73ab" }

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "8d090689be14078f2ca41c356e7bbc0af21f73ab" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
match_opt = "0.1.2"

[dev-dependencies]
indexmap = { version = "1.9.1", features = ["serde"] }
rand = "0.8.5"
tempfile = "3.3.0"
primary = { path = "../primary" }
test_utils = { path = "../test_utils" }
types = { path = "../types" }
telemetry-subscribers = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "8d090689be14078f2ca41c356e7bbc0af21f73ab" }
