[package]
name = "executor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]

[dependencies]
async-trait = "0.1.57"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.2.1"
config = { path = "../config" }
consensus = { path = "../consensus" }
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "c022a2ae23ca7cc2778293fd3b1db42e8cd02d3b" }
futures = "0.3.24"
multiaddr = "0.14.0"
primary = { path = "../primary" }
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.34"
tokio = { version = "1.20.1", features = ["sync"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tonic = "0.7.2"
tracing = "0.1.36"
prometheus = "0.13.1"
storage = { path = "../storage" }
itertools = "0.10.3"

crypto = { path = "../crypto" }
types = { path = "../types" }
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "352091e92070c2ecfcccad444361a78249ecfe59" }

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "352091e92070c2ecfcccad444361a78249ecfe59" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
match_opt = "0.1.2"

[dev-dependencies]
indexmap = { version = "1.9.1", features = ["serde"] }
rand = "0.8.5"
tempfile = "3.3.0"
test_utils = { path = "../test_utils" }
types = { path = "../types" }
telemetry-subscribers = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "352091e92070c2ecfcccad444361a78249ecfe59" }
