[package]
name = "executor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]

[dependencies]
async-trait = "0.1.53"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.1.0"
futures = "0.3.21"
rocksdb = { version = "0.18.0", features = ["snappy", "lz4", "zstd", "zlib"], default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["sync"] }
tokio-util = { version = "0.7.2", features = ["codec"] }
tracing = "0.1.34"
config = { path = "../config" }
consensus = { path = "../consensus" }
crypto = { path = "../crypto" }
primary = { path = "../primary" }
tonic = "0.7.2"
multiaddr = "0.14.0"

types = { path = "../types" }
worker = { path = "../worker" }

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "7c247967e5a5abd59ecaa75bc62b05bcdf4503fe" }
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "7c247967e5a5abd59ecaa75bc62b05bcdf4503fe" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
rand = "0.7.3"
tempfile = "3.3.0"
