[package]
name = "executor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]

[dependencies]
async-trait = "0.1.53"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.1.0"
futures = "0.3.21"
rocksdb = { version = "0.18.0", features = ["snappy", "lz4", "zstd", "zlib"], default-features = false }
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["sync"] }
tokio-util = { version = "0.7.1", features = ["codec"] }
tracing = "0.1.34"
backoff = { version ="0.4.0", features = ["tokio"]}

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "808de09203d147b43d59114b8afd9e51cbcf5778" }
config = { path = "../config" }
consensus = { path = "../consensus" }
crypto = { path = "../crypto" }
primary = { path = "../primary" }
types = { path = "../types" }
worker = { path = "../worker" }

[dev-dependencies]
rand = "0.7.3"
tempfile = "3.3.0"
