[package]
name = "narwhal-executor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]

[dependencies]
async-trait = "0.1.57"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.2.1"
config = { path = "../config", package = "narwhal-config" }
consensus = { path = "../consensus", package = "narwhal-consensus" }
fastcrypto = "0.1.2"
futures = "0.3.24"
multiaddr = "0.14.0"
primary = { path = "../primary", package = "narwhal-primary" }
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.35"
tokio = { version = "1.20.1", features = ["sync"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tonic = "0.7.2"
tracing = "0.1.36"
prometheus = "0.13.2"
backoff = { version = "0.4.0", features = ["tokio"] }
storage = { path = "../storage", package = "narwhal-storage" }
itertools = "0.10.4"

types = { path = "../types", package = "narwhal-types" }
mysten-network = "0.1.0"
network = { path = "../network", package = "narwhal-network" }
crypto = { path = "../crypto", package = "narwhal-crypto" }
anyhow = "1.0.65"

store = { version = "0.1.0", package = "typed-store" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
match_opt = "0.1.2"
rand = "0.8.5"

[dev-dependencies]
indexmap = { version = "1.9.1", features = ["serde"] }
tempfile = "3.3.0"
primary = { path = "../primary", package = "narwhal-primary" }
test_utils = { path = "../test_utils", package = "narwhal-test-utils" }
types = { path = "../types", package = "narwhal-types" }
telemetry-subscribers = "0.1.0"
