[package]
name = "consensus"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.2.1"
match_opt = "0.1.2"
rand = { version = "0.8.5", optional = true }
serde = { version = "1.0.144", features = ["derive"] }
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "9deac015fbf66e24b6da9699630e06750eaa094a" }
thiserror = "1.0.34"
tokio = { version = "1.20.1", features = ["sync"] }
tracing = "0.1.36"

config = { path = "../config" }
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "c022a2ae23ca7cc2778293fd3b1db42e8cd02d3b" }
crypto = { path = "../crypto" }
storage = { path = "../storage" }
dag = { path = "../dag" }
prometheus = "0.13.1"
types = { path = "../types" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
cfg-if = "1.0.0"

[dev-dependencies]
bincode = "1.3.3"
criterion = "0.3.6"
futures = "0.3.24"
indexmap = { version = "1.9.1", features = ["serde"] }
test_utils = { path = "../test_utils" }

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.10.1", features = ["criterion", "flamegraph"]}

[features]
default = ["rand"]
benchmark = []
pprof = []

[lib]
bench = false

[[bench]]
name = "process_certificates"
harness = false
required-features = ["benchmark", "pprof"]
