[package]
name = "consensus"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.1.0"
rand = { version = "0.7.3", optional = true }
# deactivation of bzip2 due to https://github.com/rust-rocksdb/rust-rocksdb/issues/609
rocksdb = { version = "0.18.0", features = ["snappy", "lz4", "zstd", "zlib"], default-features = false }
serde = { version = "1.0.136", features = ["derive"] }
serde_bytes = "0.11.5"
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "808de09203d147b43d59114b8afd9e51cbcf5778" }
tokio = { version = "1.17.0", features = ["sync"] }
tracing = "0.1.34"

config = { path = "../config" }
crypto = { path = "../crypto" }
types = { path = "../types" }

[dev-dependencies]
bincode = "1.3.3"
criterion = "0.3.5"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
pprof = { version = "0.8.0", features = ["criterion", "flamegraph"] }
temp_testdir = "0.2.3"

[features]
default = ["rand"]
benchmark = []

[lib]
bench = false

[[bench]]
name = "process_certificates"
harness = false
required-features = ["benchmark"]
