[package]
name = "consensus"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["sync"] }
rand = { version = "0.7.3", optional = true }
crypto = { path = "../crypto" }
config = { path = "../config" }
primary = { path = "../primary" }
blake2 = "0.9"
tracing = "0.1.31"
tokio-util = { version = "0.7.0", features = ["codec"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_bytes = "0.11.5"
futures = "0.3.21"
# deactivation of bzip2 due to https://github.com/rust-rocksdb/rust-rocksdb/issues/609
rocksdb = { version = "0.18.0", features = ["snappy", "lz4", "zstd", "zlib"], default-features = false }
bytes = "1.1.0"
async-trait = "0.1.52"
bincode = "1.3.3"
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "808de09203d147b43d59114b8afd9e51cbcf5778"}

[dev-dependencies]
bincode = "1.3.3"
criterion = "0.3.5"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
pprof = { version = "0.6.2", features = ["criterion", "flamegraph"] }
temp_testdir = "0.2"
async-trait = "0.1.53"
worker = { path = "../worker" }
thiserror = "1.0.30"

[features]
default = ["rand"]
benchmark = []

[lib]
bench = false

[[bench]]
name = "process_certificates"
harness = false
required-features = ["benchmark"]
