[package]
name = "consensus"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["sync"] }
rand = { version = "0.7.3", optional = true }
crypto = { path = "../crypto" }
config = { path = "../config" }
primary = { path = "../primary" }
tracing = "0.1.31"

[dev-dependencies]
bincode = "1.3.3"
criterion = "0.3.5"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
pprof = { version = "0.6.2", features = ["criterion", "flamegraph"] }

[features]
default = ["rand"]
benchmark = []

[lib]
bench = false

[[bench]]
name = "process_certificates"
harness = false
required-features = ["benchmark"]
