[package]
name = "consensus"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.2.1"
match_opt = "0.1.2"
rand = { version = "0.7.3", optional = true }
# deactivation of bzip2 due to https://github.com/rust-rocksdb/rust-rocksdb/issues/609
rocksdb = { version = "0.18.0", features = ["snappy", "lz4", "zstd", "zlib"], default-features = false }
serde = { version = "1.0.142", features = ["derive"] }
serde_bytes = "0.11.6"
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "d965a5a795dcdb4d1c7964acf556bc249fdc58aa" }
thiserror = "1.0.31"
tokio = { version = "1.20.1", features = ["sync"] }
tracing = "0.1.36"

config = { path = "../config" }
crypto = { path = "../crypto" }
dag = { path = "../dag" }
types = { path = "../types" }
prometheus = "0.13.1"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
futures = "0.3.21"
bincode = "1.3.3"
criterion = "0.3.6"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
test_utils = { path = "../test_utils"}
indexmap = { version = "1.9.1", features = ["serde"] }

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.10.0", features = ["criterion", "flamegraph"] }

[features]
default = ["rand"]
benchmark = []

[lib]
bench = false

[[bench]]
name = "process_certificates"
harness = false
required-features = ["benchmark", "pprof"]
