[package]
name = "consensus"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Alberto Sonnino <asonnino@fb.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.5.0", features = ["sync"] }
rand = { version = "0.7.3", optional = true}
crypto = { path = "../crypto" }
config = { path = "../config" }
primary = { path = "../primary" }
tracing = "0.1"

[dev-dependencies]
bincode = "1.3"
criterion = "0.3"
pprof = { version = "0.6", features = ["criterion", "flamegraph"] }

[features]
default = ["rand"]
benchmark = []

[lib]
bench = false

[[bench]]
name = "process_certificates"
harness = false
required-features = ["benchmark"]
