[package]
name = "worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.57"
bincode = "1.3.3"
blake2 = "0.9"
byteorder = "1.4.3"
bytes = "1.2.1"
futures = "0.3.23"
multiaddr = "0.14.0"
serde = { version = "1.0.143", features = ["derive"] }
tokio = { version = "1.20.1", features = ["sync", "rt", "macros"] }
tokio-stream = "0.1.9"
tokio-util = { version = "0.7.3", features = ["codec"] }
tonic = "0.7.2"
tower = "0.4.13"
tracing = "0.1.36"

config = { path = "../config" }
crypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "a9e58305dc463c40b9d357730203406214909f04", package = "fastcrypto" }
network = { path = "../network" }
primary = { path = "../primary" }
types = { path = "../types" }
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "8d090689be14078f2ca41c356e7bbc0af21f73ab" }
prometheus = "0.13.1"

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "8d090689be14078f2ca41c356e7bbc0af21f73ab" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
rand = "0.8.5"
tempfile = "3.3.0"
test_utils = { path = "../test_utils" }

[features]
benchmark = []
