[package]
name = "worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.0", features = ["codec"] }
ed25519-dalek = "1.0.1"
serde = { version = "1.0.136", features = ["derive"] }
bytes = "1.1.0"
bincode = "1.3.3"
futures = "0.3.21"
async-trait = "0.1.52"
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev="808de09203d147b43d59114b8afd9e51cbcf5778"}
tracing = { version = "0.1.31", features = ["log"] }

crypto = { path = "../crypto" }
config = { path = "../config" }
network = { path = "../network" }
primary = { path = "../primary" }
blake2 = "0.9"

[dev-dependencies]
rand = "0.7.3"
tempfile = "3.3.0"

[features]
benchmark = []
