[package]
name = "worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Alberto Sonnino <asonnino@fb.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.15.0", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.6.9", features = ["codec"] }
ed25519-dalek = "1.0.1"
serde = { version = "1.0.132", features = ["derive"] }
bytes = "1.1.0"
bincode = "1.3.3"
futures = "0.3.19"
async-trait = "0.1.52"
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store" }
tracing = { version = "0.1.29", features = ["log"] }

crypto = { path = "../crypto" }
config = { path = "../config" }
network = { path = "../network" }
primary = { path = "../primary" }

[dev-dependencies]
rand = "0.7.3"
tempfile = "3.2.0"

[features]
benchmark = []
