[package]
name = "worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.53"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.1.0"
ed25519-dalek = "1.0.1"
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "808de09203d147b43d59114b8afd9e51cbcf5778" }
tokio = { version = "1.17.0", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.1", features = ["codec"] }
tracing = { version = "0.1.34", features = ["log"] }

config = { path = "../config" }
crypto = { path = "../crypto" }
network = { path = "../network" }
primary = { path = "../primary" }
types = { path = "../types" }

[dev-dependencies]
rand = "0.8.5"
tempfile = "3.3.0"

[features]
benchmark = []
