[package]
name = "worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.59"
async-trait = "0.1.57"
bincode = "1.3.3"
blake2 = "0.9"
bytes = "1.2.1"
ed25519-dalek = "1.0.1"
futures = "0.3.21"
serde = { version = "1.0.141", features = ["derive"] }
tokio = { version = "1.20.1", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tracing = "0.1.36"
tonic = "0.7.2"
tokio-stream = "0.1.9"
tower = "0.4.13"
multiaddr = "0.14.0"

config = { path = "../config" }
crypto = { path = "../crypto" }
network = { path = "../network" }
primary = { path = "../primary" }
types = { path = "../types" }

store = { git = "https://github.com/mystenlabs/mysten-infra.git", package = "typed-store", rev = "d965a5a795dcdb4d1c7964acf556bc249fdc58aa" }
mysten-network = { git = "https://github.com/mystenlabs/mysten-infra.git", rev = "d965a5a795dcdb4d1c7964acf556bc249fdc58aa" }
prometheus = "0.13.1"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
arc-swap = { version = "1.5.0", features = ["serde"] }
rand = "0.7.3"
tempfile = "3.3.0"
test_utils = { path = "../test_utils" }


[features]
benchmark = []
