[package]
name = "crypto"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
base64ct = { version = "1.5.0", features = ["alloc"] }
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
eyre = "0.6.8"
rand = { version = "0.7.3", features = ["std"] }
serde = { version = "1.0.136", features = ["derive"] }
zeroize = "1.5.1"
signature = "1.5.0"
tokio = { version = "1.17.0", features = ["sync", "rt", "macros"] }
ark-bls12-377 = { version = "0.3.0", features = ["std"], optional = true }

# TODO: switch to https://github.com/celo-org/celo-bls-snark-rs 
# when https://github.com/celo-org/celo-bls-snark-rs/issues/228 is solved
celo-bls = { git = "https://github.com/huitseeker/celo-bls-snark-rs", branch = "updates-2", package = "bls-crypto", optional = true }

ark-ec = { version = "0.3.0", features = ["std"], optional = true }
ark-ff = { version = "0.3.0", features = ["std"], optional = true }
ark-serialize = { version = "0.3.0", features = ["std"], optional = true }
ark-std = { version = "0.3.0", features = ["std"], optional = true }
blake2 = "0.10"
blst = "0.3.6"
once_cell = "1.10.0"
readonly = "0.2.1"
serde_bytes = "0.11.5"
serde_with = { version = "1.13.0", optional = true }

[[bench]]
name = "crypto"
harness = false
# This doesn't seem to work with criterion, cf. https://github.com/bheisler/criterion.rs/issues/344
# For now, we have to bench by doing `cargo bench --features="batch"`.
# required-features = ["batch"]

[features]
default = ["celo"]
celo = ["ark-ec", "ark-ff", "ark-serialize", "ark-bls12-377", "ark-std", "serde_with", "celo-bls"]

[dev-dependencies]
bincode = "1.3.3"
criterion = "0.3.5"
