[package]
name = "crypto"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
base64ct = { version = "1.5.1", features = ["alloc"] }
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
eyre = "0.6.8"
hex = "0.4.3"
rand = { version = "0.7.3", features = ["std"] }
serde = { version = "1.0.139", features = ["derive"] }
zeroize = "1.5.7"
signature = "1.5.0"
tokio = { version = "1.20.1", features = ["sync", "rt", "macros"] }
ark-bls12-377 = { version = "0.3.0", features = ["std"], optional = true }
hkdf = { version = "0.12.3", features = ["std"] }
serde_with = "1.14.0"
rust_secp256k1 = { version = "0.24.0", package = "secp256k1", features = ["recovery", "rand-std", "bitcoin_hashes", "global-context"] }

# TODO: switch to https://github.com/celo-org/celo-bls-snark-rs 
# when https://github.com/celo-org/celo-bls-snark-rs/issues/228 is solved
celo-bls = { git = "https://github.com/huitseeker/celo-bls-snark-rs", branch = "updates-2", package = "bls-crypto", optional = true }

ark-ec = { version = "0.3.0", features = ["std"], optional = true }
ark-ff = { version = "0.3.0", features = ["std"], optional = true }
ark-serialize = { version = "0.3.0", features = ["std"], optional = true }
ark-std = { version = "0.3.0", features = ["std"], optional = true }
blake2 = "0.9"
blst = "0.3.10"
once_cell = "1.13.0"
readonly = "0.2.1"
serde_bytes = "0.11.6"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
digest = "0.10.3"

[[bench]]
name = "crypto"
harness = false
# This doesn't seem to work with criterion, cf. https://github.com/bheisler/criterion.rs/issues/344
# For now, we have to bench by doing `cargo bench --features="batch"`.
# required-features = ["batch"]

[features]
default = []
celo = ["ark-ec", "ark-ff", "ark-serialize", "ark-bls12-377", "ark-std", "celo-bls"]
copy_key = []

[dev-dependencies]
bincode = "1.3.3"
criterion = "0.3.5"
sha3 = "0.10.1"
hex-literal = "0.3.4"
proptest = "1.0.0"
proptest-derive = "0.3.0"
serde_json = "1.0.80"
k256 = { version = "0.11.3", features = ["ecdsa", "sha256", "keccak256"] }
