[package]
name = "crypto"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition = "2018"
publish = false

[dependencies]
base64ct = { version = "1.3", features = ["alloc"] }
tokio = { version = "1.5.0", features = ["sync", "rt", "macros"] }
ed25519-dalek = { version = "1.0.1", features = ["batch"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.7.3"
base64 = "0.13.0"
zeroize = "1.4.3"

[dev-dependencies]
serde_test = "1.0"