name: auto-merge & finishing steps for dependabot

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions-rs/toolchain@v1
      - name: Install cargo-hakari, and cache the binary
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-hakari
          locked: true
      - name: run cargo-hakari
        run: |
          cargo hakari generate
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        # using secrets.AUTOMERGE_TOKEN in the below is key to re-trigger CI
        run: |
          git config --global user.name 'Francois Garillot'
          git config --global user.email 'francois@mystenlabs.com'
          git remote set-url origin https://x-access-token:${{ secrets.AUTOMERGE_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "chore(deps): cargo hakari"
          git push
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
        with:
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
          command: 'squash and merge'
          target: minor
      - name: Enable auto-merge for Dependabot PRs on patch versions
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

