name: Update Dependencies
on:
  ## Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:
  schedule:
    # Update on every hour at 10 past the hour
    - cron:  '10 * * * *'

jobs:
  update-dep:
    runs-on: ubuntu-latest
    # Important settings as we don't want to open a PR when the update fails
    continue-on-error: false
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - uses: bmwill/rust-cache@v1 # Fork of 'Swatinem/rust-cache' which allows caching additional paths
      - name: Install cargo-hakari, and cache the binary
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-hakari
          locked: true
      - name: Update the Fastcrypto & Mysten-infra pointers
        run: |
          scripts/update_dependencies.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.FC_AUTO_UPDATE }}
            commit-message: chore(deps) Update the Fastcrypto & Mysten-infra pointers
            title: chore(deps) Update the Fastcrypto & Mysten-infra pointers
            body: |
              - Update Fastcrypto & Mysten-infra pointers
  
              Auto-generated by [create-pull-request][1] an the scripts/update_dependencies.sh script
  
              [1]: https://github.com/peter-evans/create-pull-request
            branch: update-fastcrypto
