name: Miscellaneous Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Protobuf format
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '14'
  
      - name: Lint shell, Docker and protobuf
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Select file types to lint. Python and Rust linters are configured separately.
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          # Enable after fixing proto lint issues.
          # VALIDATE_PROTOBUF: true
