name: Check scripts, Docker file and profobuf

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    name: Lint shell, docker and protobuf files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@latest
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run clang-format for protobuf
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '14'
          fallback-style: 'Google'
  
      - name: Lint Code Base
        uses: github/super-linter@slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Select file types to lint. Python and Rust linters are configured separately.
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_PROTOBUF: true
