name: Python lints

on:
  push:
    branches:
      - main
      - devnet
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            benchmark:
              - 'benchmark/**'
      - name: Set up Python 3.8
        if: steps.filter.outputs.benchmark == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install flake8, pip-audit
        if: steps.filter.outputs.benchmark == 'true'
        run: pip install flake8 pip-audit
      - name: Run lint
        if: steps.filter.outputs.benchmark == 'true'
        run: |
          flake8 benchmark --count --max-complexity=14 --max-line-length=127 --statistics
      - name: Run audit
        if: steps.filter.outputs.benchmark == 'true'
        run: |
          pip-audit -r benchmark/requirements.txt
