name: Check scripts

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  build:
    name: Check shell scripts
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error